core/urls.py
from django.urls import path
# from .views import (
#     products,
#     home,
#     checkout)
from django.conf.urls.static import static
from django.conf import settings
from . import views
app_name = 'core'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('product/<slug>/', views.ItemDetailView.as_view(), name='product'),
    path('checkout', views.checkout, name='checkout'),
    path('add-to-cart/<slug>/', views.add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', views.remove_from_cart, name='remove-from-cart'),
    path('order-summary', views.OrderSummaryView.as_view(), name= 'order-summary'),
    path('remove-single-item-from-cart/<slug>/', views.remove_single_item_from_cart, name='remove_single_item_from_cart'),
]

e_commerce_django/urls.py
from django.conf import settings
# from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core'))
]
# if settings.DEBUG:
#     import  debug_toolbar
#     urlpatterns += [path('__debug__', include((debug_toolbar.urls)))]

core/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import  reverse
CATEGORY_CHOICES = (
    ('S', 'Shirt'),
    ('SW', 'Sport wear'),
    ('OW', 'Outwear')
)

LABEL_CHOICES = (
    ('P', 'bg-primary'),
    ('S', 'bg-success'),
    ('D', 'bg-danger')
)


class Item(models.Model):

    title = models.CharField(max_length=255)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    slug = models.SlugField()
    item_description = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.quantity} of {self.item.title}'

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price()-self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()

        return total

core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Item, OrderItem, Order
from django.views.generic import ListView, DetailView, View

from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.


class HomeView(ListView):
    model = Item
    paginate_by = 10
    template_name = "home.html"


# def home(request):
#     context = {
#         'items': Item.objects.all()
#     }
#     return render(request, 'home.html', context)


class ItemDetailView(DetailView):
    model = Item
    template_name = 'product.html'


def products(request):
    context = {
        'items': Item.objects.all()
    }
    return render(request, "product.html", context)


def checkout(request):
    return render(request, 'checkout.html')


# adding/removing orderItem
@login_required
def add_to_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    # find or create new order item belong to user's order
    order_item, created = OrderItem.objects.get_or_create(
        item=item,
        user=request.user,
        ordered=False
    )
    # find the order exist
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(item__slug=item.slug).exists():
            order_item.quantity += 1
            order_item.save()
            messages.info(request, 'This item quantity was increase :>')
            return redirect("core:order-summary")
        else:
            order.items.add(order_item)
            messages.info(request, 'This item was added to your cart :>')
            return redirect("core:order-summary")
    else:
        order = Order.objects.create(user=request.user, ordered_date=timezone.now())
        order.items.add(order_item)
        messages.info(request, 'This item was added to your cart :>')
    return redirect("core:product", slug=slug)

@login_required
def remove_from_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    # find the order exist
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(item=item, user=request.user, ordered=False)[0]
            order.items.remove(order_item)
            order_item.delete()
            messages.info(request, 'This item was remove from your cart:>')
            return redirect("core:order-summary")
        else:
            messages.info(request, 'This item was not in your cart :>')
    else:
        messages.info(request, 'You do not have an active order :>')
    return redirect("core:product", slug=slug)

class OrderSummaryView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            context = {
                'object': order
            }
            return render(self.request, 'order_summary.html', context)

        except:
            messages.error(self.request, 'You do not have an active order')
            return redirect("/")

@login_required
def remove_single_item_from_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    # find the order exist
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(item=item, user=request.user, ordered=False)[0]
            order_item.quantity -= 1
            order_item.save()
            # order_item.delete()
            messages.info(request, 'This item quantity was updated:>')
            return redirect("core:order-summary")
        else:
            messages.info(request, 'This item was not in your cart :>')
    else:
        messages.info(request, 'You do not have an active order :>')
    return redirect("core:product", slug=slug)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">

    {#  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">#}
  <style type="text/css">
    html,
    body,
    header,
    {#.carousel {#}
    {#  height: 60vh;#}
    {#}#}

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      {#.carousel {#}
      {#  height: 100vh;#}
      {#}#}
    }

  </style>
</head>

{% include "navbar.html" %}

<body>

    <div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
    </div>

    {% block content %}
    {% endblock content %}

    {% block extra_body %}
    {% endblock %}

    {% include "footer.html" %}
    {% include "scripts.html" %}

    {% block extra_scripts %}
    {% endblock extra_scripts %}
    <!-- Bootstrap 5 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- MDB -->
    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>

    <!-- Custom scripts -->
{#    <script type="text/javascript" src="js/script.js"></script>#}
</body>
</html>

templates/footer.html
<footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com/mdbootstrap" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/MDBootstrap" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="https://dribbble.com/mdbootstrap" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="https://pinterest.com/mdbootstrap" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="http://codepen.io/mdbootstrap/" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
    </div>
    <!--/.Copyright-->

  </footer>

templates/home.html
{% extends 'base.html' %}
{% block content %}
        <style>
{##}
{#    .card {#}
{#     box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;#}
{#    }#}
{#    .footer-cta {#}
{#      box-shadow: rgba(0, 0, 0, 0.15) 0px 5px 15px;#}
{#    }#}
    {#.price {#}
    {#  color: #263238;#}
    {#  font-size: 24px;#}
    {#}#}

    {#.card-title {#}
    {#color:#263238#}
    {#}#}

    {#.sale {#}
    {#  color: #E53935#}
    {#}#}

    {#.sale-badge {#}
    {#  background-color: #E53935#}
    {#}#}
    </style>
<!--Main layout-->
<main>
<div class="container">
  <!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark mt-3 mb-5 shadow p-2" style="background-color: #607D8B">
  <!-- Container wrapper -->
  <div class="container-fluid">

    <!-- Navbar brand -->
    <a class="navbar-brand" href="#">Categories:</a>

    <!-- Toggle button -->
    <button
       class="navbar-toggler"
       type="button"
       data-mdb-toggle="collapse"
       data-mdb-target="#navbarSupportedContent2"
       aria-controls="navbarSupportedContent2"
       aria-expanded="false"
       aria-label="Toggle navigation">
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent2">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <!-- Link -->
        <li class="nav-item acitve">
          <a class="nav-link text-white" href="#">All</a>
        </li>
        <li class="nav-item">
              <a class="nav-link text-white" href="#">Shirts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-white" href="#">Sport wears</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-white" href="#">Outwears</a>
            </li>

      </ul>

      <!-- Search -->
      <form class="w-auto py-1" style="max-width: 12rem">
        <input type="search" class="form-control rounded-0" placeholder="Search" aria-label="Search">
      </form>

    </div>
  </div>
  <!-- Container wrapper -->
</nav>
<!-- Navbar -->

<!-- Products -->
  <section>
  <div class="text-center">
    <div class="row">
        {% for item in object_list %}
      <div class="col-lg-3 col-md-6 mb-4">
        <div class="card">
          <div class="bg-image hover-zoom ripple ripple-surface ripple-surface-light"
            data-mdb-ripple-color="light">
            <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg"
              class="w-100" />
            <a href="{{ item.get_absolute_url }}">
              <div class="mask">
                <div class="d-flex justify-content-start align-items-end h-100">
                  <h5><span class="badge ms-2 {{ item.get_label_display }}">NEW</span></h5>
                </div>
              </div>
              <div class="hover-overlay">
                <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
              </div>
            </a>
          </div>
          <div class="card-body">
            <a href="{{ item.get_absolute_url }}" class="text-reset">
              <h5 class="card-title mb-2">{{ item.title }}</h5>
            </a>
            <a href="" class="text-reset ">
              <p>{{ item.get_category_display }}</p>
            </a>

            <h6 class="mb-3 price blue-text">
              {% if item.discount_price %}
                    <del class="text-danger">{{ item.price }}</del>
                  {{item.discount_price }}$
                  {% else %}
                  {{item.price }}$
              {% endif %}

            </h6>
          </div>
        </div>
      </div>
        {% endfor %}

    </div>

  </div>
</section>

<!-- Pagination -->
{% if is_paginated %}
  <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-3">
  <ul class="pagination">
      {% if page_obj.has_previous0 %}
    <li class="page-item">
      <a class="page-link" href="?page={{page_obj.previous_page_number  }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
      {% endif %}
    <li class="page-item active">
        <a class="page-link" href="?page={{ page_obj.number }}">
            <span class="sr-only">{{ page_obj.number }}</span>
        </a>
    </li>

    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}
<!-- Pagination -->
</div>
</main>
 <!--Main layout-->
{% endblock content %}

templates/item_list.html
{% extends "base.html" %}

{% block content %}
<h2>Here is the list of items</h2>
    {% for item in items %}
        {{ item }}
    {% endfor%}
{% endblock %}

templates/navbar.html
{% load cart_template_tags %}
<!-- Navbar -->
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-white">
    <!-- Container wrapper -->
    <div class="container">
        <!-- Toggle button -->
        <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarSupportedContent1" aria-controls="navbarSupportedContent1" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fas fa-bars"></i>
        </button>

        <!-- Collapsible wrapper -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent1">
            <!-- Navbar brand -->
            <a class="navbar-brand mt-2 mt-sm-0" href="/">
                <strong class="blue-text">E-commerce</strong>
            </a>
            <!-- Left links -->
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/checkout">Checkout</a>
                </li>
            </ul>
            <!-- Left links -->
        </div>
        <!-- Collapsible wrapper -->

        <!-- Right elements -->
        <div class="d-flex align-items-center">
            <!-- Icon -->
            {% if request.user.is_authenticated %}
                <a class="nav-link me-3" href="{% url 'core:order-summary' %}">
                <i class="fas fa-shopping-cart"></i>
                <span class="badge rounded-pill badge-notification bg-danger">{{ request.user|cart_item_count }}</span>
                </a>
                <a class="nav-link me-3" href="{% url 'account_logout' %}">
                <span class="">Logout</span>
                </a>
            {% else %}
                <a class="nav-link me-3" href="{% url 'account_login' %}">
                Login
                </a>
                <a class="nav-link me-3" href="{% url 'account_signup' %}">
                <span class="">Sign up</span>
                </a>
            {% endif %} 

        </div>
        <!-- Right elements -->
    </div>
    <!-- Container wrapper -->
</nav>
<!-- Navbar -->

templates/order_summary.html
{% extends 'base.html' %}
{% block content %}

<!--Main layout-->
<main>
<div class="container">
    <h2>Order Summary</h2>
    <table class="table">
      <thead>
        <tr>
            <th>#</th>
          <th scope="col">Item titel</th>
          <th scope="col">Price</th>
          <th scope="col">Quantity</th>
          <th scope="col">Total Item Price</th>
        </tr>
      </thead>
      <tbody>
      {% for order_item in object.items.all %}
          <tr>
          <th>{{ forloop.counter }}</th>
          <th scope="row">{{ order_item.item.title }}</th>
          <td>{{ order_item.item.price }}</td>
          <td>
              <a href="{% url 'core:remove_single_item_from_cart' order_item.item.slug %}"><i class="fas fa-minus"></i></a>
              {{ order_item.quantity }}
              <a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus"></i></a>
          </td>
          <td>
              {% if order_item.item.discount_price %}
                  ${{ order_item.get_total_discount_item_price }}
                  <span class="badge badge-primary">(Saving ${{ order_item.get_amount_saved }} )</span>
              {% else %}
                  ${{ order_item.get_total_item_price }}
              {% endif %}
              <a class="float-end text-dark" href="{% url 'core:remove-from-cart' order_item.item.slug %}">
                  <i class="fas fa-trash"></i>
              </a>

          </td>

        </tr>
          {% empty %}
          <tr>
          <td colspan="5"> Your cart is empty</td>
          </tr>
      {% endfor %}
      {% if object.get_total %}
          <tr>
            <td colspan="4"><strong>Order Total</strong></td>
            <td>{{ object.get_total }}</td>
          </tr>
            <tr>
            <td colspan="5">
                <a href="/" class="btn btn-secondary">Continue Shopping</a>
                <a href="/checkout" class="btn btn-warning float-end">Proceed to checkout</a>
            </td>
            </tr>
          {% else %}
          <tr>
              <td colspan="5">
                <a href="/" class="btn btn-secondary">Continue Shopping</a>
              </td>
          </tr>
      {% endif %}

      </tbody>
    </table>
</div>
</main>
 <!--Main layout-->
{% endblock content %}

templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!--Main layout-->
<main class="mt-5 pt-4">
    <div class="container mt-5">
        <!--Grid row-->
        <div class="row">
            <!--Grid column-->
            <div class="col-md-6 mb-4">
                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/14.jpg" class="img-fluid" alt="" />
            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-md-6 mb-4">
                <!--Content-->
                <div class="p-4">
                    <div class="mb-3">
                        <a href="">
                            <span class="badge ms-2 {{ item.get_label_display }}">{{ object.get_category_display }}</span>
                        </a>
{#                        <a href="">#}
{#                            <span class="badge bg-info me-1">New</span>#}
{#                        </a>#}
{#                        <a href="">#}
{#                            <span class="badge bg-danger me-1">Bestseller</span>#}
{#                        </a>#}
                    </div>

                    <p class="lead">
                        {% if object.discount_price %}
                            <span class="me-1">
                            <del>${{ object.discount_price }}</del>
                        </span>
                        {% endif %}
                        <span>${{ object.price }}</span>
                    </p>

                    <strong><p style="font-size: 20px;">Description</p></strong>

                    <p>{{ object.item_description }}</p>

                    <a class="btn btn-primary ms-1" href="{{ object.get_add_to_cart }}">
                            Add to cart
                            <i class="fas fa-shopping-cart ms-1"></i>
                    </a>
                    <a class="btn btn-danger ms-1" href="{{ object.get_remove_from_cart }}">
                            Remove from cart
                            <i class="fas fa-shopping-cart ms-1"></i>
                    </a>
                </div>
                <!--Content-->
            </div>
            <!--Grid column-->
        </div>
        <!--Grid row-->

        <hr />

        <!--Grid row-->
        <div class="row d-flex justify-content-center">
            <!--Grid column-->
            <div class="col-md-6 text-center">
                <h4 class="my-4 h4">Additional information</h4>

                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit voluptates, quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>
            </div>
            <!--Grid column-->
        </div>
        <!--Grid row-->

        <!--Grid row-->
        <div class="row">
            <!--Grid column-->
            <div class="col-lg-4 col-md-12 mb-4">
                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="" />
            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-lg-4 col-md-6 mb-4">
                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="" />
            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-lg-4 col-md-6 mb-4">
                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="" />
            </div>
            <!--Grid column-->
        </div>
        <!--Grid row-->
    </div>
</main>
<!--Main layout-->
{% endblock content %}

templates/scripts.html
{% load static %}

<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
{#<!-- Initializations -->#}
{#<script type="text/javascript">#}
{#  // Animations initialization#}
{#  new WOW().init();#}
{##}
{#</script>#}